# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
