# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_delete_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pas', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
