# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20180330_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
