# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_images_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='davp_constraint',
            name='pic',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='pic',
            field=models.ImageField(upload_to=b''),
        ),
    ]
