# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-07 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_auto_20180331_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='davp_constraint',
            name='caption',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
